"""empty message

Revision ID: 069ca80caaeb
Revises: 
Create Date: 2025-03-24 15:41:14.782171

"""

from alembic import op
import sqlalchemy as sa
from fastapi_storages.integrations.sqlalchemy import ImageType


# revision identifiers, used by Alembic.
revision = '069ca80caaeb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('first_name', sa.String(), nullable=False),
        sa.Column('last_name', sa.String(), nullable=False),
        sa.Column('score', sa.Numeric(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('password', sa.String(), nullable=False),
        sa.Column(
            'status', sa.Enum('NOT_VERIFIED', 'VERIFIED', 'SUSPECTED', 'BANNED', name='userstatus'), nullable=False
        ),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
        sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_table(
        'user_favorites',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('car_id', sa.Uuid(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_favorites_user_id_users')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_user_favorites')),
    )
    op.create_index('ix_user_favorite_user_id', 'user_favorites', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_favorites_id'), 'user_favorites', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_favorites_id'), table_name='user_favorites')
    op.drop_index('ix_user_favorite_user_id', table_name='user_favorites')
    op.drop_table('user_favorites')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
